### ISSUE TITLE
Auto complete issue final form

### ISSUE THREAD

**Issue by naveennsit** [TrejGun/jwt-based-authorization-for-nestjs#112]
https://stackoverflow.com/questions/59832331/why-checkbox-is-not-checked-in-react?noredirect=1#comment105801358_59832331

I am trying to implement Auto complete having checkbox.

https://material-ui.com/components/autocomplete/#autocomplete

**Comment by TrejGun** [comment]
this repo has nothing in common with my autocomplete solution so i'm going to close it. 
however i saw same issue in my blog repo, lets track it there
